import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";

const lato = Roboto({
    weight: ["100", "300", "400", "700", "900"],
    subsets: ["latin"],
    variable: "--font-roboto",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "bg-background min-h-screen font-sans antialiased",
                    lato.variable
                )}
            >
                <CartProvider>{children}</CartProvider>
            </body>
        </html>
    );
}
